### PR TITLE
Added endpoint path style option

### PR DESCRIPTION
**Pull request by stereu**

### CODE REVIEW

**Comment by mrAceT** [comment]
Could this also work? (and be more compact)
```
if(!$CONFIG['objectstore']['arguments']['use_path_style']){
     $CONFIG['objectstore']['arguments']['use_path_style'] = false;
}
$s3 = new S3Client([
    'version' => 'latest',
    'endpoint' => 'https://'.$CONFIG['objectstore']['arguments']['hostname'].'/'.$bucket,
    'bucket_endpoint' => true,
    'use_path_style_endpoint' => $CONFIG['objectstore']['arguments']['use_path_style'],
    'region'  => $CONFIG['objectstore']['arguments']['region'],
    'credentials' => [
        'key' => $CONFIG['objectstore']['arguments']['key'],
        'secret' => $CONFIG['objectstore']['arguments']['secret'],
    ],
]);
```

**Comment by mrAceT** [comment]
AD: small question, is this required by your S3-proivider or is there an other reason you have set this option?

**Comment by stereu** [comment]
This won't work as in path-style the bucketname must be after the hostname and a slash. Without path-style the bucket name has to be a subdomain before the hostname. You can see it in the different endpoint definitions.

This option is required by some S3 providers in europe for example virtuozzo.

**Comment by mrAceT** [comment]
Ah! the endpoint is also different! Check!

**Pull request merged**
